version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
     working_directory: ~/email_services

     docker:
       - image: cimg/node:15.14.0-browsers
         auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD
        
     steps:
       - checkout
       - add_ssh_keys:
             fingerprints:
                 - "bb:c0:f8:62:d5:63:ba:40:2e:9c:8c:2e:0f:23:6c:f5"
       - restore_cache: # special step to restore the dependency cache
             keys:
                    - dependency-cache-{{ checksum "package.json" }}
                    # fallback to using the latest cache if no exact match is found
                    - dependency-cache-
       - run:
           name: Setup Dependencies
           command: npm install 
       - save_cache:
                paths:
                    - ~/node_modules
                key: dependency-cache-{{ checksum "package.json" }} 
       - run:
                name: Run tests
                command: npm test
                when: always
   
       - run:
                name: Setup Code Climate test-reporter
                command: |
                    # download test reporter as a static binary
                    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                    chmod +x ./cc-test-reporter
                    ./cc-test-reporter before-build
                when: always

       - store_artifacts: # upload test coverage as artifact
                path: ./coverage/lcov.info
       - store_test_results:
                path: ~/email_services/test-results
      
     
     
workflows:
  node-tests:
    jobs:
      - build