version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
     environment:
      CC_TEST_REPORTER_ID: e7f57bdfbbf935860f35d140bf7c38717550f50dffc2ab50ed51b1914f41d35d
     docker:
       - image: circleci/node:8
   
     steps:
       - checkout
       - restore_cache: # special step to restore the dependency cache
             keys:
                    - dependency-cache-{{ checksum "package.json" }}
                    # fallback to using the latest cache if no exact match is found
                    - dependency-cache-
       - run:
           name: Setup Dependencies
           command: npm install 
       - save_cache:
                paths:
                    - node_modules
                key: dependency-cache-{{ checksum "package.json" }} 
       - run:
                name: Run tests
                command: npm test
                when: always
   
       - run:
                name: Setup Code Climate test-reporter
                command: |
                    # download test reporter as a static binary
                    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                    chmod +x ./cc-test-reporter
                    ./cc-test-reporter before-build
                when: always

       - store_artifacts: # upload test coverage as artifact
                path: ./coverage/lcov.info
       - run:
                name: Send coverage report to Code Climate
                command:
                    # nyc report requires that nyc has already been run,
                    # which creates the .nyc_output folder containing necessary data
                    ./cc-test-reporter after-build -t lcov
     
     
workflows:
  node-tests:
    jobs:
      - build